all: course  multif observe


course : course.c
	 gcc -Wall -Wextra course.c  -o course

multif: multif.c
	gcc -Wall -Wextra  multif.c -o multif
observe: observe.c
	gcc -Wall -Wextra observe.c -o observe 